// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id and email as seen by the MCP server. Useful for connection health checks.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_customers_default = defineTool2({
  name: "list_customers",
  title: "List customers",
  description: "List customers visible to the signed-in user, optionally filtered by a search string on name/company/email.",
  inputSchema: {
    search: z.string().optional().describe("Optional substring to match against name, company, or email."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("customers").select("id, name, company, email, phone, lead_status, source, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search && search.trim()) {
      const s = search.trim().replace(/[%,]/g, "");
      q = q.or(`name.ilike.%${s}%,company.ilike.%${s}%,email.ilike.%${s}%`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-inquiries.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_inquiries_default = defineTool3({
  name: "list_inquiries",
  title: "List inquiries",
  description: "List inquiries (pipeline items) visible to the signed-in user, optionally filtered by status or customer.",
  inputSchema: {
    status: z2.string().optional().describe("Optional status filter (e.g. active, paused, po, complete, cancelled)."),
    customer_id: z2.string().uuid().optional().describe("Optional customer UUID to filter by."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, customer_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("pipeline_items").select("id, name, description, status, customer_id, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (customer_id) q = q.eq("customer_id", customer_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { inquiries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_products_default = defineTool4({
  name: "list_products",
  title: "List products",
  description: "List products visible to the signed-in user, optionally filtered by a name search or inquiry (customer_rfq) id.",
  inputSchema: {
    search: z3.string().optional().describe("Optional substring to match on product name."),
    customer_rfq_id: z3.string().uuid().optional().describe("Optional inquiry/RFQ UUID to filter by."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, customer_rfq_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("products").select("id, name, product_type, customer_rfq_id, quantity, design_stage, quote_stage, sample_stage, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search && search.trim()) {
      const s = search.trim().replace(/[%,]/g, "");
      q = q.ilike("name", `%${s}%`);
    }
    if (customer_rfq_id) q = q.eq("customer_rfq_id", customer_rfq_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool5({
  name: "list_tasks",
  title: "List tasks",
  description: "List tasks visible to the signed-in user. Filter by completion state or due-date window.",
  inputSchema: {
    only_open: z4.boolean().optional().describe("If true, exclude completed tasks."),
    limit: z4.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_open, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("tasks").select("id, title, description, status, priority, due_date, assigned_to, created_at").order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 50);
    if (only_open) q = q.neq("status", "completed");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-cogs-item.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var COGS_TYPES = [
  "Raw Piece",
  "Subcontracting",
  "Finishing Materials",
  "Packaging",
  "Hardware",
  "Accessories"
];
var add_cogs_item_default = defineTool6({
  name: "add_cogs_item",
  title: "Add COGS item to a product",
  description: "Add a COGS line to a specific product. Resolve the product first with `list_products` (or pass its UUID). Example: to add '520/- raw mango tray' to the HFM Serving Tray, call with product_id, cogs_type='Raw Piece', component_name='Raw Mango Tray', unit_cost_inr=520. cogs_type must be one of: Raw Piece, Subcontracting, Finishing Materials, Packaging, Hardware, Accessories.",
  inputSchema: {
    product_id: z5.string().uuid().describe("UUID of the target product."),
    cogs_type: z5.enum(COGS_TYPES).describe("Category of the COGS line."),
    component_name: z5.string().min(1).describe("Display name of the component, e.g. 'Raw Mango Tray'."),
    unit_cost_inr: z5.number().nonnegative().describe("Unit cost in INR."),
    vendor_name: z5.string().optional().describe("Optional vendor name."),
    units: z5.string().optional().describe("Unit of measure (default 'pc')."),
    components_per_product: z5.number().nonnegative().optional().describe("Quantity per product (default 1)."),
    waste_factor: z5.number().min(0).max(1).optional().describe("Waste factor as a decimal (e.g. 0.05 for 5%)."),
    include: z5.enum(["Yes", "No"]).optional().describe("Whether to include this line in totals (default Yes).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data: product, error: prodErr } = await sb.from("products").select("id, name").eq("id", input.product_id).maybeSingle();
    if (prodErr) return { content: [{ type: "text", text: prodErr.message }], isError: true };
    if (!product) {
      return {
        content: [{ type: "text", text: `Product ${input.product_id} not found or not accessible.` }],
        isError: true
      };
    }
    const { data: maxRow } = await sb.from("cogs_items").select("sort_order").eq("product_id", input.product_id).order("sort_order", { ascending: false }).limit(1).maybeSingle();
    const nextSort = (maxRow?.sort_order ?? -1) + 1;
    const row = {
      product_id: input.product_id,
      cogs_type: input.cogs_type,
      component_name: input.component_name,
      unit_cost_inr: input.unit_cost_inr,
      vendor_name: input.vendor_name ?? null,
      units: input.units ?? "pc",
      components_per_product: input.components_per_product ?? 1,
      waste_factor: input.waste_factor ?? 0,
      include: input.include ?? "Yes",
      is_auto_calculated: false,
      sort_order: nextSort
    };
    const { data, error } = await sb.from("cogs_items").insert(row).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: `Added COGS line "${input.component_name}" (${input.cogs_type}, \u20B9${input.unit_cost_inr}) to product "${product.name}".`
        }
      ],
      structuredContent: { cogs_item: data, product: { id: product.id, name: product.name } }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yunhcegxsgxloasvwugx";
var mcp_default = defineMcp({
  name: "product-hq-mcp",
  title: "Product HQ",
  version: "0.1.0",
  instructions: "Tools for the Product HQ costing & CRM app. Use `whoami` to verify the connection. Read tools: `list_customers`, `list_inquiries`, `list_products`, `list_tasks`. Write tools: `add_cogs_item` (first call `list_products` to resolve the target product's UUID by name, then add the COGS line). All tools run under the signed-in user's Row-Level Security policies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_customers_default, list_inquiries_default, list_products_default, list_tasks_default, add_cogs_item_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
